

name: mix3r
channels:
  - conda-forge
  - numba
  - rapidsai
dependencies:
  - python=3.12
  - conda-pack=0.8.0
  - numpy=2.0.2
  - scipy=1.14.1
  - numba=0.60.0
  - cuda-nvcc=12.4.131
  - cuda-nvrtc=12.4.127
  - pandas=2.2.3
  - matplotlib-base=3.9.2
  - ipython=8.28.0
  - notebook=7.2.2
  - r=4.4
  - r-essentials=4.4
  - r-irkernel=1.3.2
  - r-eulerr=7.0.2
  - numba::numba=0.60.0
  - numba::icc_rt=2020.2
  - rapidsai::pynvjitlink=0.3.0
